### ISSUE TITLE
TypeError: google.people is not a function

### ISSUE THREAD

**Issue by TJbotSA2** [DrewGregory/tjcalendar#2]
I'm having some trouble running tjcal.js. The error I am receiving is 

/home/pi/tjcalendar/tjcal.js:4
var googlePeople = google.people('v1');
                          ^

TypeError: google.people is not a function
    at Object.<anonymous> (/home/pi/tjcalendar/tjcal.js:4:27)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
    at bootstrap_node.js:507:3

The Tjcal.js file has not been modified. My file directories can be found below. 

pi@y: /tjcalendar $ ls 
client_secret.json  credentials.json  package.json   TJCalendar Flowchart.png
config.default.js   LICENSE           quickstart.js  tjcal.js
config.js           node_modules      README.md      workspace.json

pi@y: /tjcalendar $ cd node_modules
pi@y: /tjcalendar/node_modules $ ls
ajv                         function-bind          nan
asn1                        gcp-metadata           node-forge
assert                      getpass                node-raspistill
assert-plus                 @google                oauth-sign
asyncawait                  googleapis             object.assign
asynckit                    google-auth-library    object-keys
aws4                        google-p12-pem         object.omit
aws-sign2                   gtoken                 object.pick
axios                       har-schema             os-tmpdir
bcrypt-pbkdf                har-validator          performance-now
bignumber.js                has-symbols            pify
bindings                    hawk                   pigpio
bluebird                    hnp                    pseudomap
boom                        hoek                   punycode
buffer-equal-constant-time  httperror              qs
buffer-from                 http-signature         request
caseless                    image-type             retry-axios
co                          inherits               rimraf
color-model                 is-buffer              rpi-ws281x-native
colornames                  is-extendable          safe-buffer
colors                      isobject               safer-buffer
combined-stream             is-plain-object        semaphore
cookie                      isstream               sleep
core-util-is                is-typedarray          sntp
cryptiles                   jsbn                   solr-client
csv-stringify               json-bigint            sound-player
cycle                       jsonify                sshpk
dashdash                    jsonparse              stack-trace
debug                       json-schema            stringstream
define-properties           json-schema-traverse   string-template
delayed-stream              json-stable-stringify  temp
duplexer                    JSONStream             through
ecc-jsbn                    json-stringify-safe    tjbot
ecdsa-sig-formatter         jsprim                 tough-cookie
extend                      jwa                    tunnel-agent
extsprintf                  jws                    tweetnacl
eyes                        lodash                 typedarray-to-buffer
fast-deep-equal             lodash.get             @types
fast-json-stable-stringify  lodash.isstring        util
fibers                      lodash.noop            uuid
fifo                        lru-cache              vcap_services
file-type                   mic                    verror
follow-redirects            mime                   watson-developer-cloud
foreach                     mime-db                websocket
forever-agent               mime-types             winston
form-data                   moment                 yaeti
fs                          ms                     yallist

**Comment by DrewGregory** [comment]
Hello! Thank you for letting me know. After some research, it seems that Google APIs now require destructuring (see [here](https://stackoverflow.com/questions/48762090/google-gmail-is-giving-an-error-typeerror-google-gmail-is-not-a-function)). Try changing the line `
var google = require('googleapis');` to `var {google} = require('googleapis');`. In the meantime, I will do a more through investigation and quite a bit of code cleanup 😄

**Comment by DrewGregory** [comment]
Ignore the previous comment: I destructuring was actually slightly different. I pushed the import changes. Unfortunately, I don't have a TJBot near me right now, so let me know if it works!
